# name: MBIA
# services:
#   backend:
#     image: mbiabackend
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "5000:5000"
#     volumes:
#       - .:/app
#     environment:
#       - FLASK_APP=app.py
#       - FLASK_ENV=development
#       - DATABASE_URL=